name: Java Unit Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Build Project
        run: mvn clean compile

      - name: Run Unit Tests
        run: mvn test